micronaut:
  application:
    name: pixKeymanagerGrpc
  http:
    client:
      log-level: DEBUG

grpc:
  server:
    port: ${SERVER_GRPC_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pixkeymanager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

itau:
  clientes: http://localhost:9091/api/v1/clientes
  contas:
    url: http://localhost:9091

bcb:
  pix:
    url: http://localhost:8082